---
version: '3.7'
services:
  scrape:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: scrape
    ports:
      - 7000:7000
    env_file:
      - ./.scrape.env
    networks:
      - proxy
      - wordpress
networks:
  proxy:
    external: true
  wordpress:
    external: true
