---
version: '3.7'
services:
  scrape:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: scrape
    ports:
      - 6079:6079
    env_file:
      - ./.env
    volumes:
      - ./scrape-logs:/app/src/logs
    networks:
      - proxy
      - wordpress
networks:
  proxy:
    external: true
  wordpress:
    external: true
